from typing import Protocol

from sqlalchemy import Engine

from src.modules.data_catalog.domain.entities import CatalogEntry, DataSource


class IExtractor(Protocol):
    def extract(self, table_name: str) -> dict: ...
    def list_tables(self) -> list[str]: ...


class IEnricher(Protocol):
    def enrich(self, raw_metadata: dict, data_source_id: str, host: str) -> CatalogEntry: ...


class ICatalogRepository(Protocol):
    def upsert(self, entry: CatalogEntry) -> None: ...
    def get_all(self, data_source_id: str | None = None) -> list[CatalogEntry]: ...
    def get_by_table(self, data_source_id: str, table_name: str) -> CatalogEntry | None: ...
    def get_data_sources(self) -> list[str]: ...


class IDataSourceRepository(Protocol):
    def set_connection(self, host: str, port: int, user: str, password: str) -> list[DataSource]: ...
    def get_all(self) -> list[DataSource]: ...
    def get_by_id(self, data_source_id: str) -> DataSource | None: ...
    def get_engine(self, data_source: DataSource) -> Engine: ...
